[workspace]
resolver = "3"
members = ["user/upac-cli", "user/sign-cli", "user/setup-cli", "lib/macro", "lib/abi", "lib/lib" , "lib/pki", "lib/types", "lib/setup", "booters/uki", "booters/systemd-boot", "booters/grub", "booters/refind", "decoders/alpm", "decoders/deb", "decoders/rpm", "decoders/xbps"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.98"

license = "LGPL-3.0-or-later WITH LGPL-3.0-linking-exception"
license-file = "LICENSES/LGPL-3.0-or-later"

readme = "README.md"
homepage = "https://github.com/SmoothTeam/upac"
repository = "https://github.com/SmoothTeam/upac"

keywords = ["package-manager", "installer", "cli", "linux"]
categories = ["command-line-utilities", "command-line-interface"]

[workspace.lints.rust]
explicit_outlives_requirements = "warn"
unused_qualifications = "warn"
unexpected_cfgs = "deny"

[workspace.lints.clippy]
cloned_instead_of_copied = "warn"
dbg_macro = "warn"
str_to_string = "warn"

[workspace.dependencies]
upac-lib = { path = "lib/lib", default-features = false }
upac-macro        = { path = "lib/macro" }
upac-types        = { path = "lib/types" }
upac-abi          = { path = "lib/abi" }
upac-pki          = { path = "lib/pki" }
upac-setup        = { path = "lib/setup" }
upac-uki          = { path = "booters/uki", default-features = false }
upac-systemd-boot = { path = "booters/systemd-boot", default-features = false }
upac-grub         = { path = "booters/grub", default-features = false }
upac-refind       = { path = "booters/refind", default-features = false }
upac-decoders-alpm = { path = "decoders/alpm", package = "alpm", default-features = false }
upac-decoders-deb  = { path = "decoders/deb", package = "deb", default-features = false }
upac-decoders-rpm  = { path = "decoders/rpm", package = "rpm", default-features = false }
upac-decoders-xbps = { path = "decoders/xbps", package = "xbps", default-features = false }

composefs-oci = { version = "0.9.0", features = ["composefs-boot", "boot", "tar"] }
nix           = { version = "0.31.3", features = ["mount", "sched", "fs", "net"] }
gettext-rs    = { version = "0.8", features = ["gettext-system"] }
composefs     = { version = "0.9.0", features = ["tempfile"] }
clap          = { version = "4.6.1", features = ["derive"] }
uuid          = { version = "1", features = ["v4"] }
serde         = { version = "1", features = ["derive"] }
syn           = { version = "3", features = ["full"] }
ctrlc         = { version = "3.5.2", features = ["termination"] }

colored        = "3.1.1"
libloading     = "0.9"
proc-macro2    = "1"
toml           = "1.1.2"
sha2           = "0.11"
anyhow         = "1"
quote          = "1"
composefs-boot = "0.9.0"
indicatif      = "0.18.4"
efivar         = "2.0.0"
tempfile       = "3"
ar             = "0.9.0"
flate2         = "1.1.9"
tar            = "0.4.46"
xz2            = "0.1.7"
zstd           = "0.13.3"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "unpacked"
incremental = true

[profile.dev.package."*"]
opt-level = 2

[profile.release]
codegen-units = 1
opt-level = 3

lto = true
strip = true
debug-assertions = false

[profile.release-x86-64-v1]
inherits = "release"

[profile.release-x86-64-v2]
inherits = "release"

[profile.release-x86-64-v3]
inherits = "release"

[profile.release-x86-64-v4]
inherits = "release"
