# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 JustPav
#
# SPDX-License-Identifier: LGPL-3.0-or-later

[package]
name = "upac-uki"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
upac-abi = { workspace = true }
efivar   = { workspace = true }

uuid = "1.24.1"

[build-dependencies]
toml = { workspace = true }
