# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 SmoothTeam
#
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

[package]
name = "upac-lib-deploy"
description = "upac's deployment partition: sysroot discovery, prefix and config deploys, boot entries"
version.workspace = true

edition.workspace = true
rust-version.workspace = true

license.workspace = true

readme.workspace = true
homepage.workspace = true
repository.workspace = true

keywords.workspace = true
categories.workspace = true

include = ["/src", "lib.toml", "build.rs"]

[lints]
workspace = true

[lib]
name = "upac_deploy"

[dependencies]
upac-lib-types     = { workspace = true }
upac-lib-abi       = { workspace = true }
upac-lib-composefs = { workspace = true }
upac-lib-database  = { workspace = true }

composefs      = { workspace = true }
composefs-boot = { workspace = true }
anyhow         = { workspace = true }
nix            = { workspace = true }
serde          = { workspace = true }
uuid           = { workspace = true }

procfs = { version = "0.18.0", default-features = false }

serde_json = "1.0.151"

[dev-dependencies]
tempfile = { workspace = true }

[build-dependencies]
toml = { workspace = true }
