# SPDX-FileCopyrightText: 2026 JustPav
#
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "upac-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Package manager for installing any type of package in Linux, as well as registering binary file rollbacks based on composefs, written in Rust"

[[bin]]
name = "up"
path = "src/main.rs"

[dependencies]
upac-abi = { workspace = true }

gettext-rs = { workspace = true }
libloading = { workspace = true }
colored    = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
clap       = { workspace = true }
toml       = { workspace = true }

ctrlc = { version = "3.5.2", features = ["termination"] }
strum = { version = "0.28.0", features = ["derive"] }

indicatif = { version = "0.18.4" }
chrono    = { version = "0.4" }
sha2      = { version = "0.11" }
hex       = { version = "0.4" }
