# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 SmoothTeam
#
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

[package]
name = "upac-lib-database"
description = "upac's embedded redb package database: package meta, file ownership and declarative trigger stores"
version.workspace = true

edition.workspace = true
rust-version.workspace = true

license.workspace = true

readme.workspace = true
homepage.workspace = true
repository.workspace = true

keywords.workspace = true
categories.workspace = true

include = ["/src", "lib.toml", "build.rs"]

[lints]
workspace = true

[lib]
name = "upac_database"

[dependencies]
upac-lib-types = { workspace = true }
upac-lib-abi   = { workspace = true }

uuid = { workspace = true }

redb = { version = "4.1.0", features = ["uuid"] }

twox-hash = "2.1.3"

[build-dependencies]
toml = { workspace = true }
