# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 JustPav
#
# SPDX-License-Identifier: LGPL-3.0-or-later

[package]
name = "upac-lib"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
license = "LGPL-3.0-or-later"
description = "Core library implementing upac's package management logic (composefs-based atomic deploys) and exposing it via a C ABI"

[lib]
name = "upac"
crate-type = ["cdylib", "rlib"]

[dependencies]
upac-abi = { workspace = true }
upac-macro = { workspace = true }

twox-hash = "2.1.3"
rsblkid = "0.4"
rsmount = "0.2"

nix = { version = "0.31.3", features = ["mount", "sched", "fs", "net"] }
libloading = "0.9"

composefs = { version = "0.7.0", features = ["tempfile"] }
composefs-boot = { version = "0.7.0" }
composefs-oci = { version = "0.7.0", features = ["composefs-boot", "boot", "tar"] }

redb = { version = "4.1.0", features = ["uuid"] }
uuid = { version = "1", features = ["v4"] }

tokio = { version = "1", features = ["rt"] }

serde = { version = "1", features = ["derive"] }
toml = "0.8"

[build-dependencies]
toml = "0.8"
