# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 JustPav
#
# SPDX-License-Identifier: LGPL-3.0-or-later

[package]
name = "upac-lib"
description = "Core library implementing upac's package management logic (composefs-based atomic deploys) and exposing it via a C ABI"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "upac"
crate-type = ["cdylib", "rlib"]

[dependencies]
upac-macro = { workspace = true }
upac-types = { workspace = true }
upac-abi   = { workspace = true }
upac-pki   = { workspace = true }

libloading = { workspace = true }
anyhow     = { workspace = true }
serde      = { workspace = true }
toml       = { workspace = true }
sha2       = { workspace = true }

composefs-oci = { version = "0.9.0", features = ["composefs-boot", "boot", "tar"] }
nix           = { version = "0.31.3", features = ["mount", "sched", "fs", "net"] }
composefs     = { version = "0.9.0", features = ["tempfile"] }
redb          = { version = "4.1.0", features = ["uuid"] }
tokio         = { version = "1", features = ["rt"] }
uuid          = { version = "1", features = ["v4"] }

composefs-boot        = { version = "0.9.0" }
linux-kernel-cmdline  = "0.1.1"
serde_json            = "1.0.151"
twox-hash             = "2.1.3"
rsblkid               = "0.4"
rsmount               = "0.2"
regex                 = "1"
quick-xml             = "0.41.0"
mime                  = "0.3.17"
hex                   = "0.4"

[build-dependencies]
toml = { workspace = true }
