# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 SmoothTeam
#
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

[package]
name = "upac-lib"
description = "Core library implementing upac's package management logic (composefs-based atomic deploys) and exposing it via a C ABI"
version.workspace = true

edition.workspace = true
rust-version.workspace = true

license.workspace = true

readme.workspace = true
homepage.workspace = true
repository.workspace = true

keywords.workspace = true
categories.workspace = true

include = ["/src", "lib.toml", "build.rs"]

[lints]
workspace = true

[lib]
name = "upac"
crate-type = ["cdylib", "rlib"]

[dependencies]
upac-lib-macro          = { workspace = true }
upac-lib-types          = { workspace = true }
upac-lib-abi            = { workspace = true }
upac-lib-orchestrator   = { workspace = true }
upac-lib-composefs      = { workspace = true }
upac-lib-database       = { workspace = true }
upac-lib-deploy         = { workspace = true }
upac-lib-decoder-loader = { workspace = true }
upac-lib-hooks          = { workspace = true }
upac-lib-boot-loader    = { workspace = true }

composefs = { workspace = true }
uuid      = { workspace = true }
quick-xml = { workspace = true }

regex = "1"

[build-dependencies]
toml = { workspace = true }

[features]
default = ["dynamic-plugins"]

dynamic-plugins = ["upac-lib-decoder-loader/dynamic-plugins", "upac-lib-boot-loader/dynamic-plugins"]

builtin-uki          = ["upac-lib-boot-loader/builtin-uki"]
builtin-systemd-boot = ["upac-lib-boot-loader/builtin-systemd-boot"]
builtin-grub         = ["upac-lib-boot-loader/builtin-grub"]
builtin-refind       = ["upac-lib-boot-loader/builtin-refind"]

builtin-alpm = ["upac-lib-decoder-loader/builtin-alpm"]
builtin-deb  = ["upac-lib-decoder-loader/builtin-deb"]
builtin-rpm  = ["upac-lib-decoder-loader/builtin-rpm"]
builtin-xbps = ["upac-lib-decoder-loader/builtin-xbps"]

builtin-all-booters  = ["upac-lib-boot-loader/builtin-all-booters"]
builtin-all-decoders = ["upac-lib-decoder-loader/builtin-all-decoders"]
builtin-all          = ["builtin-all-booters", "builtin-all-decoders"]
