# SPDX-FileCopyrightText: 2026 JustPav
# SPDX-FileCopyrightText: 2026 SmoothTeam
#
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "upac-sign-cli"
description = "CLI tool for signing upac hook files (and other artifacts) with Ed25519 certificates"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
license = "GPL-3.0-only"

[[bin]]
name = "up-si"
path = "src/main.rs"

[dependencies]
upac-pki   = { workspace = true }

gettext-rs = { workspace = true }
colored    = { workspace = true }
anyhow     = { workspace = true }
clap       = { workspace = true }
