# SPDX-FileCopyrightText: 2026 JustPav
#
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "upac-sign-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "CLI tool for signing upac hook files (and other artifacts) with Ed25519 certificates"

[[bin]]
name = "up-si"
path = "src/main.rs"

[dependencies]
upac-pki = { workspace = true }

gettext-rs = { version = "0.7", features = ["gettext-system"] }
clap = { version = "4.6.1", features = ["derive"] }

colored = { version = "3.1.1" }
anyhow = "1"
