name: Make package for Alpm Aarch64 Musl

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Update base via apt
        run: sudo apt-get update

      - name: Install base via apk
        run: sudo apt-get install -y libglib2.0-dev pkg-config

      - name: Install OSTree via apk
        run: sudo apt-get install -y libostree-dev

      - name: Install Zig via apk
        run: sudo apt-get install -y zig

      - name: Install Rust via apk
        run: sudo apt-get install -y rustс cargo

      - name: Install Make via apk
        run: sudo apt-get install -y make

      - name: Build package
        run: make build MODE=release

      - name: Store binaries
        uses: actions/upload-artifact@v4
        with:
          name: upac-binaries
          path: build/
          retention-days: 5
