name: Make package for Alpm Aarch64 Musl

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest # Используем Arch
    steps:
      - name: Install Zig via pacman
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm zig

      - name: Build package
        run: make pkg-arch CPU=x86_64_v3 MODE=release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: upac-alpm-aarch64-musl
          path: pkg/*
