name: Make package for Alpm Aarch64 Musl

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pkg-config via apk
        run: apk add --no-cache base-devel

      - name: Install OSTree via apk
        run: apk add --no-cache ostree

      - name: Install Zig via apk
        run: apk add --no-cache zig

      - name: Install Latest Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: cargo

      - name: Install Make via apk
        run: apk add --no-cache make

      - name: Build package
        run: make build MODE=release

      - name: Store binaries
        uses: actions/upload-artifact@v4
        with:
          name: upac-binaries
          path: build/
          retention-days: 5
