name: Rust CI Clippy and lint
on:
  push:
    branches: [main]
    paths-ignore: ["**.md", "doc/**", "LICENSES/**", "REUSE.toml"]
  pull_request:
    branches: [main]
    paths-ignore: ["**.md", "doc/**", "LICENSES/**", "REUSE.toml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build, Test, and Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libblkid-dev libmount-dev clang mold gettext

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: |
          cargo clippy --workspace --all-targets -- -D warnings

      - name: Lint style
        run: cargo xtask lint-style
