name: Package Arch (ARM)

on:
  workflow_run:
    workflows: ["Build aarch64"]
    types: [completed]

jobs:
  pkg-arch-arm:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name
      == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download ARM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: upac-binaries-aarch64
          path: build/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Package
        run: |
          useradd -m builder
          chown -R builder:builder .
          su builder -c "make pkg-arch"

      - name: Upload Arch Package (ARM)
        uses: actions/upload-artifact@v4
        with:
          name: arch-package-aarch64
          path: pkg/*.pkg.tar.zst
          retention-days: 5
