name: Make package DEB (aarch64)
on:
  workflow_run:
    workflows: ["Build aarch64"]
    types: [completed]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  pkg-deb-arm:
    if: >
      github.event_name != 'workflow_run' ||
      (github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_repository.full_name == github.repository)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download ARM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: upac-binaries-aarch64
          path: build/
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev make

      - name: Build DEB Package
        run: |
          make pkg-deb

      - name: Upload DEB Package (ARM)
        uses: actions/upload-artifact@v4
        with:
          name: deb-package-aarch64
          path: pkg/*.deb
          retention-days: 5
