name: Make package RPM (x86-64)
on:
  workflow_run:
    workflows: ["Build x86_64"]
    types: [completed]

jobs:
  pkg-rpm:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name
      == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        cpu: [x86_64, x86_64_v2, x86_64_v3, x86_64_v4]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download compiled binaries (${{ matrix.cpu }})
        uses: actions/download-artifact@v4
        with:
          name: upac-binaries-${{ matrix.cpu }}
          path: build/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install RPM tools
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm make

      - name: Build RPM package (${{ matrix.cpu }})
        run: make pkg-rpm

      - name: Upload RPM Package (${{ matrix.cpu }})
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package-ubuntu-${{ matrix.cpu }}
          path: pkg/*.rpm
          retention-days: 5
