name: Make package Arch (aarch64)
on:
  workflow_run:
    workflows: ["Build aarch64"]
    types: [completed]
  workflow_call:

jobs:
  pkg-arch-arm:
    if: >
      github.event_name != 'workflow_run' ||
      (github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_repository.full_name == github.repository)
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download ARM Artifacts
        uses: actions/download-artifact@v4
        with:
          name: upac-binaries-aarch64
          path: build/
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies via pacman
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel sudo

      - name: Build Package
        run: |
          useradd -m builder
          chown -R builder:builder .
          su builder -c "make pkg-arch"

      - name: Upload Arch Package (ARM)
        uses: actions/upload-artifact@v4
        with:
          name: arch-package-aarch64
          path: pkg/*.pkg.tar.zst
          retention-days: 5
