name: Make package Arch
on:
  workflow_run:
    workflows: ["Build x86_64"]
    types: [completed]

jobs:
  pkg-arch:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name
      == 'workflow_dispatch' }}

    strategy:
      fail-fast: false
      matrix:
        cpu: [x86_64, x86_64_v2, x86_64_v3, x86_64_v4]

    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download compiled binaries (${{ matrix.cpu }})
        uses: actions/download-artifact@v4
        with:
          name: upac-binaries-${{ matrix.cpu }}
          path: build/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies via pacman
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel sudo

      - name: Build ALPM package (${{ matrix.cpu }})
        run: |
          useradd -m builder
          chown -R builder:builder .
          su builder -c "make pkg-arch"

      - name: Upload Arch Package (${{ matrix.cpu }})
        uses: actions/upload-artifact@v4
        with:
          name: arch-package-${{ matrix.cpu }}
          path: pkg/*.pkg.tar.zst
          retention-days: 5
