name: Make package DEB (x86-64)
on:
  workflow_run:
    workflows: ["Build x86_64"]
    types: [completed]
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  pkg-deb:
    if: >
      github.event_name != 'workflow_run' ||
      (github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_repository.full_name == github.repository)
    strategy:
      fail-fast: false
      matrix:
        cpu: [x86_64, x86_64_v2, x86_64_v3, x86_64_v4]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download compiled binaries (${{ matrix.cpu }})
        uses: actions/download-artifact@v4
        with:
          name: upac-binaries-${{ matrix.cpu }}
          path: build/
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev make

      - name: Build DEB package (${{ matrix.cpu }})
        run: |
          make pkg-deb

      - name: Upload DEB Package (${{ matrix.cpu }})
        uses: actions/upload-artifact@v4
        with:
          name: deb-package-${{ matrix.cpu }}
          path: pkg/*.deb
          retention-days: 5
